<?php
require __DIR__ . '/../includes/admin-functions.php';
require __DIR__ . '/../includes/admin-builds.php';
$build = admin_record('SELECT b.*,u.username FROM saved_builds b JOIN users u ON u.id=b.user_id WHERE b.id = ?',[admin_id($_GET['id'] ?? null)]);
$summary = admin_build_summary($build['build_data']);
admin_start($build['build_name'],'Saved ' . $build['created_at']);
?>
<p>Owner: <a href="user-view.php?id=<?= (int)$build['user_id'] ?>"><?= e($build['username']) ?></a></p>
<?php if ($summary['missing']): ?><div class="alert alert-warning">Missing components: <?= e(implode(', ',$summary['missing'])) ?>. Compatibility and totals are incomplete.</div><?php endif; ?>
<div class="row g-4"><div class="col-lg-8"><section class="admin-panel"><h2 class="h5">Selected components</h2><div class="table-responsive"><table class="table"><thead><tr><th>Category</th><th>Component</th><th>Current price</th><th>Status</th></tr></thead><tbody><?php foreach ($summary['parts'] as $type=>$part): $part['category']=$type; ?><tr><td><?= e(component_categories()[$type]) ?></td><td><a href="<?= e(admin_product_link($part)) ?>"><?= e($part['name']) ?></a></td><td><?= e(admin_money($part['price'])) ?></td><td><?= admin_badge($part['status']) ?></td></tr><?php endforeach; ?></tbody></table></div></section><section class="admin-panel mt-4"><h2 class="h5">Compatibility</h2><?php foreach ($summary['checks'] as $label=>$check): ?><div class="compatibility-row"><strong><?= e($label) ?></strong> <?= admin_badge($check['status']) ?><p class="text-muted mb-0"><?= e($check['message']) ?></p></div><?php endforeach; if (!$summary['checks']): ?><p>No checks available. Add components to this build first.</p><?php endif; ?><p class="text-muted small mt-3 mb-0">Missing specifications remain unknown. These are basic checks, not a guarantee of full compatibility.</p></section></div><div class="col-lg-4"><section class="admin-panel"><h2 class="h5">Build summary</h2><dl class="order-totals"><div><dt>Current price<?= $summary['missing'] || $summary['missingPrice'] ? ' (partial)' : '' ?></dt><dd><?= e(admin_money(cents_decimal($summary['cents']))) ?></dd></div><div><dt>Estimated power</dt><dd><?= $summary['watts'] ?> W</dd></div><div><dt>Recommended PSU</dt><dd><?= $summary['recommended'] ?> W</dd></div></dl><p class="text-muted small">Power includes estimates where specifications are missing. Prices reflect the current catalog, not a purchase.</p></section></div></div><?php admin_end(); ?>
